# Generated by Django 4.2.11 on 2024-04-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
            ],
        ),
    ]
